# Generated by Django 4.2.5 on 2023-09-18 23:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas1', '0003_usuario_remove_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='persona_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='ventas1.persona'),
            preserve_default=False,
        ),
    ]
