# Generated by Django 4.2.5 on 2023-09-18 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas1', '0004_usuario_persona_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='persona_id',
        ),
    ]
